### ISSUE TITLE
fix swagger for non aiohug routes

### ISSUE THREAD

**Issue by nonamenix** [aiohug/aiohug#7]
```
Traceback (most recent call last):
  File "/home/d_ivanof/.virtualenvs/vortex/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 390, in start
    resp = await self._request_handler(request)
  File "/home/d_ivanof/.virtualenvs/vortex/lib/python3.6/site-packages/aiohttp/web_app.py", line 352, in _handle
    resp = await handler(request)
  File "/home/d_ivanof/.virtualenvs/vortex/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 106, in impl
    return await handler(request)
  File "/home/d_ivanof/.virtualenvs/vortex/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 96, in impl
    return await handler(request)
  File "/home/d_ivanof/.virtualenvs/vortex/lib/python3.6/site-packages/aiohug/__init__.py", line 17, in _handler
    resp = await handler(**kwargs)
  File "/home/d_ivanof/.virtualenvs/vortex/lib/python3.6/site-packages/aiohug/swagger/handlers.py", line 14, in swagger_json
    return swagger.generate_swagger(request.app)
  File "/home/d_ivanof/.virtualenvs/vortex/lib/python3.6/site-packages/aiohug/swagger/__init__.py", line 134, in generate_swagger
    parameters = get_parameters(url, handler, spec)
  File "/home/d_ivanof/.virtualenvs/vortex/lib/python3.6/site-packages/aiohug/swagger/__init__.py", line 44, in get_parameters
    defaults = get_default_args(handler._original_handler)
AttributeError: 'function' object has no attribute '_original_handler'
```

```python
try:
    handler_spec["parameters"] = get_parameters(url, handler, spec)
except AttributeError:
    pass
```

**Comment by nonamenix** [comment]
Move it to aiohug_swagger
